const prefix = 'iconfont'
const iconMap = {
  home: `${prefix} iconic_home_24px`,
  search: `${prefix} iconic_search_24px`,
  date: `${prefix} iconic_date_range_24px`,
  edit: `${prefix} iconic_mode_edit_24px`,
  refresh: `${prefix} iconic_refresh_24px`,
  close: `${prefix} iconic_close_24px`,
  cancel: `${prefix} iconic_cancel_24px`,
  arrowRight: `${prefix} iconic_keyboard_arrow_right_24px`,
  arrowLeft: `${prefix} iconic_keyboard_arrow_left_24px`,
  arrowDropUp: `${prefix} iconic_arrow_drop_up_24px`,
  arrowDropDown: `${prefix} iconic_arrow_drop_down_24px`,
  account: `${prefix} iconic_account_box_24px`,
  key: `${prefix} iconic_vpn_key_24px`,
  person: `${prefix} iconic_person_24px`,
  personAdd: `${prefix} iconic_person_add_24px`,
  personOutline: `${prefix} iconic_person_outline_24px`,
  lockOutline: `${prefix} iconic_lock_outline_24px`,
  analytics: `${prefix} iconanalytics-24px`,
  errorOutline: `${prefix} iconic_error_outline_24px`,
  notifications: `${prefix} iconnotification_important-24px3`,
  campaign: `${prefix} iconcampaign-24px`,
  supervisor: `${prefix} iconcampaign-24px`,
  history: `${prefix} iconic_history_24px`,
  phone: `${prefix} iconic_local_phone_24px`,
  pdf: `${prefix} iconic_picture_as_pdf_24px`,
  visibility: `${prefix} iconic_visibility_24px`,
  visibilityOff: `${prefix} iconic_visibility_off_24px`,
  logout: `${prefix} iconic_exit_to_app_px`,
  undo: `${prefix} iconic_undo_24px`,
  done: `${prefix} iconic_done_24px`,
  doneAll: `${prefix} iconic_done_all_24px`,
  unfoldMore: `${prefix} iconic_unfold_more_24px`,
  unfoldLess: `${prefix} iconic_unfold_less_24px`,
  share: `${prefix} iconic_share_24px`,
  sync: `${prefix} iconic_sync_24px`,
  delete: `${prefix} iconic_delete_24px`,
  add: `${prefix} iconic_add_24px`,
  addCircle: `${prefix} iconic_add_circle_24px`,
  addCircleOutline: `${prefix} iconic_add_circle_outline_24px`,
}

export default iconMap